before_install:
    - "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-full texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended latex-xcolor exlive-math-extra dvipng"
script:
    - pdflatex resume.tex
deploy:
    provider: releases
    file:
    - resume.pdf
