before_install:
	- "sudo apt-get update && sudo apt-get install --no-install-recommends textlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
script:
	- pdflatex resume.tex
deploy:
	file:
		- resume.pdf
