dist: trusty
before_install:
    - "sudo add-apt-repository ppa:jonathonf/texlive-2016 && sudo apt-get update && sudo apt-get install --no-install-recommends texlive-full texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended latex-xcolor texlive-xetex texlive-math-extra dvipng texlive-latex3"
script:
    - xelatex -interaction=nonstopmode resume.tex
deploy:
    provider: releases
    file:
    - resume.pdf
